apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: juanestebane/propath-api-gateway:latest
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"
            - name: PATH_MICROSERVICE_HOST
              value: "path-management"
            - name: PATH_MICROSERVICE_PORT
              value: "3001"
            - name: USER_MICROSERVICE_HOST
              value: "user-management"
            - name: USER_MICROSERVICE_PORT
              value: "3003"
            - name: AUTH_MICROSERVICE_HOST
              value: "auth-service"
            - name: AUTH_MICROSERVICE_PORT
              value: "3002"
            - name: AI_MICROSERVICE_HOST
              value: "ai-service"
            - name: AI_MICROSERVICE_PORT
              value: "3004"
            - name: SMTP_MICROSERVICE_HOST
              value: "smtp-service"
            - name: SMTP_MICROSERVICE_PORT
              value: "3005"
            - name: NODE_ENV
              value: "development"
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
spec:
  type: NodePort
  selector:
    app: api-gateway
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30080  # Acceso desde minikube host: localhost:30080

