apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-management
  template:
    metadata:
      labels:
        app: user-management
    spec:
      containers:
        - name: user-management
          image: notkuello/propath-backend-user-management:latest
          ports:
            - containerPort: 3003
          env:
            - name: PORT
              value: "3003"
            - name: HOST
              value: "0.0.0.0"
            - name: DB_HOST
              value: "postgres"
            - name: DB_PORT
              value: "5432"
            - name: DB_USERNAME
              value: "propath"
            - name: DB_PASSWORD
              value: "propath123"
            - name: DB_NAME
              value: "propath_db"
            - name: DB_SYNC
              value: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: user-management
spec:
  selector:
    app: user-management
  ports:
    - protocol: TCP
      port: 3003
      targetPort: 3003
  type: ClusterIP

